FROM hasura/graphql-engine:v2.45.1

# External Services
ENV STRAPI_API_URL=$STRAPI_API_URL
ENV CLERK_BACKEND_API=$CLERK_BACKEND_API
ENV SUPABASE_POSTGRES_URL=$SUPABASE_POSTGRES_URL

# Hasura Development
ENV HASURA_GRAPHQL_DEV_MODE=$HASURA_GRAPHQL_DEV_MODE
ENV HASURA_GRAPHQL_ENABLE_CONSOLE=$HASURA_GRAPHQL_ENABLE_CONSOLE

# Hasura Config
ENV HASURA_GRAPHQL_ENDPOINT=$HASURA_GRAPHQL_ENDPOINT
ENV HASURA_GRAPHQL_JWT_SECRET=$HASURA_GRAPHQL_JWT_SECRET
ENV HASURA_GRAPHQL_CORS_DOMAIN=$HASURA_GRAPHQL_CORS_DOMAIN
ENV HASURA_GRAPHQL_ADMIN_SECRET=$HASURA_GRAPHQL_ADMIN_SECRET
ENV HASURA_GRAPHQL_PG_CONNECTIONS=$HASURA_GRAPHQL_PG_CONNECTIONS
ENV HASURA_GRAPHQL_ENABLE_TELEMETRY=$HASURA_GRAPHQL_ENABLE_TELEMETRY
ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE=$HASURA_GRAPHQL_UNAUTHORIZED_ROLE
ENV HASURA_GRAPHQL_ENABLE_APOLLO_FEDERATION=$HASURA_GRAPHQL_ENABLE_APOLLO_FEDERATION
ENV HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS=$HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS
ENV HASURA_GRAPHQL_METADATA_DEFAULTS=$HASURA_GRAPHQL_METADATA_DEFAULTS
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES=$HASURA_GRAPHQL_ENABLED_LOG_TYPES
ENV HASURA_GRAPHQL_ENABLE_PERSISTED_QUERIES=$HASURA_GRAPHQL_ENABLE_PERSISTED_QUERIES

# Destacked API
ENV DESTACKED_SECRET_KEY=$DESTACKED_SECRET_KEY

# Change $DATABASE_URL to your heroku postgres URL if you're not using
# the primary postgres instance in your app
CMD graphql-engine \
    --database-url $DATABASE_URL \
    serve \
    --server-port $PORT


## Comment the command above and use the command below to
## enable an access-key and an auth-hook
## Recommended that you set the access-key as a environment variable in heroku
#CMD graphql-engine \
#    --database-url $DATABASE_URL \
#    serve \
#    --server-port $PORT \
#    --access-key XXXXX \
#    --auth-hook https://myapp.com/hasura-webhook 
#
